### ISSUE TITLE
[BUG] "server_names_hash_bucket_size" directive is not allowed here in

### ISSUE THREAD

**Issue by JustDevZero** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#256] opened 2019-05-18 16:57 UTC
**Describe the bug**
The includes are being added outsite of nginx http {} zone, producing an 'emerg' that don't let nginx start up.

**To Reproduce**
Just run nstall-ngxblocker -x and see that try to start nginx or check syntax for find that there are errors.

**Expected behavior**
Run normally with the parameter properly added instead of breaking current installation.

**Screenshots**

**Server (please complete the following information):**
 - OS: Alpine Linux (Inside Docker)
 - Nginx Version: nginx/1.16.0
 - Other Environments: 
 - Any applicable error messages.

2019/05/18 16:23:53 [emerg] 1#1: "server_names_hash_bucket_size" directive is not allowed here in /etc/nginx/conf.d/botblocker-nginx-settings.conf:16
nginx: [emerg] "server_names_hash_bucket_size" directive is not allowed here in /etc/nginx/conf.d/botblocker-nginx-settings.conf:16
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by JustDevZero** [comment] 2019-05-18 17:03
![screenshot](https://user-images.githubusercontent.com/172759/57972792-a1091a00-799f-11e9-93c5-5eb2cbf6dfab.png)
![move](https://user-images.githubusercontent.com/172759/57972793-a1091a00-799f-11e9-9656-205576519603.png)

**Comment by mitchellkrogza** [comment] 2019-05-19 08:06
Hi @JustDevZero the only recommended place for the insertion of the includes is within the http {} and not server {} block, has been this way since day one. Not sure what the install-ngblocker script did to produce that error. Please can you post your exact command lines and installation steps you used to produce this behavior.

We only ever do the includes in the http{} block, its way I designed this from the onset. In fact I designed it in such a way that you do not even need to put any includes into your nginx.conf but rather to rely on  them being included by Nginx through the default include that already comes with every single nginx.conf file which is `	include /etc/nginx/conf.d/*.conf;` it's a reason those includes are located in conf.d in the first place.

**Comment by itoffshore** [comment] 2019-05-19 10:48
@JustDevZero - can you provide your `nginx.conf` ?

**Comment by JustDevZero** [comment] 2019-05-19 11:28
@mitchellkrogza That's what I thought, to share it will all the hosts, but some how it failed.

Just compiled nginx from sources (due to I want to test the bleeding edge), but nginx.conf is the same, attached you will the nginx.conf as @itoffshore asks for it.

Attached you will find both, the default one and the one modified by the script after:

```
wget -q -O /usr/local/sbin/install-ngxblocker https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/install-ngxblocker && \
chmod +x /usr/local/sbin/install-ngxblocker && \
/usr/local/sbin/install-ngxblocker -x && \
/usr/local/sbin/setup-ngxblocker -x && \
/usr/local/sbin/update-ngxblocker -n

```

As you will see, not only it's being inserted outsite of http {} block, but with wrong tabulation :(

[nginx-bad-block.conf.txt](https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/files/3195011/nginx-bad-block.conf.txt)
[nginx.conf.txt](https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/files/3195012/nginx.conf.txt)

**Comment by mitchellkrogza** [comment] 2019-05-31 05:59
Any update on this @JustDevZero @itoffshore

**Comment by JustDevZero** [comment] 2019-06-01 07:45
As for my part didn't try to reinstall it since the otherday.

I can try again and let you know about.

**Comment by mitchellkrogza** [comment] 2019-06-20 14:17
@itoffshore this appears to be related to > https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/266

See: https://travis-ci.org/mitchellkrogza/nginx-ultimate-bad-bot-blocker/builds/548217400#L3513

We have a number of bugs in the installer and updater and I am not sure when they creeped in because all of the build tests were previously working 100% :thinking:

**Comment by itoffshore** [comment] 2019-06-20 15:06
the format of `nginx.conf` has changed - this is the cause of the problems

**Comment by mitchellkrogza** [comment] 2019-06-20 15:13
Oh bugger 🙈

**Comment by mitchellkrogza** [comment] 2019-06-22 09:23
@itoffshore any ETA on a fix for this, or can you point me to which part of the code and I can see if I can fiddle with it?

**Comment by itoffshore** [comment] 2019-06-23 13:48
the problem is with line `429`:

`line=$(find_includes $MAIN_CONF include last http first '\}' last )`

**Comment by mitchellkrogza** [comment] 2019-06-25 18:07
@itoffshore  I did have a peek at it but not entirely sure what to try and fix been too busy with a lot of changes as you can see from the past few days commits  hopefully tomorrow can try fix this and complete my barrage of very thorough testing need the 3 disabled build tests to come back online

**Comment by mitchellkrogza** [comment] 2019-07-02 10:24
@JustDevZero I think I have this issue almost sorted now. Some final tests in progress to check the inserting of includes on various different Distro versions of nginx.conf.

**Closed** 2019-07-02 13:43 UTC
Labels: Bug

**Comment by mitchellkrogza** [comment] 2019-07-02 18:31
@JustDevZero latest setup-ngxblocker in root fixes this and tested on a variety of different nginx.conf files from different repos. Please test and confirm

**Comment by JustDevZero** [comment] 2019-07-02 18:33
I'll test it and let you know anything as soon as possible. Thanks for
looking at this again.

**Comment by Bluscream** [comment] 2020-06-09 19:24
I had the same issue just now
