### ISSUE TITLE
-bash: /usr/local/sbin/update-ngxblocker: No such file or directory [FeeBSD]

### ISSUE THREAD

**Issue by alsyundawy** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#212] opened 2018-09-24 11:44 UTC
[root@xxx ~]# /usr/local/sbin/update-ngxblocker
-bash: /usr/local/sbin/update-ngxblocker: No such file or directory
[root@xxx ~]# /usr/local/sbin/setup-ngxblocker
-bash: /usr/local/sbin/setup-ngxblocker: No such file or directory

**Comment by itoffshore** [comment] 2018-10-15 12:17
duplicate of https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/213

**Closed by itoffshore** 2018-10-15 12:17 UTC
