### ISSUE TITLE
False Positive: 138.43.60.0/22

### ISSUE THREAD

**Issue by tmanting** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#358] opened 2020-02-19 19:08 UTC
## Paste the full Domain name / Referrer String here

```

Paste the full Referrer String here (paste in between the ```     ``` markers)

```

## Is this for Addition / Removal?

 - [ ] Addition
 - [X] Removal

## Post Log Excerpt to show User-Agent behavior (10-20 lines is enough)

```

Post log excerpt here (paste in between the ```     ``` markers)

```

## Additional information

Hello,
A company that uses your service suggest I post a PR here because our mutual customers are being blocked by nginx. 
My name is Tom Manting and I am the CIO of HomeWorks Connect, an Internet Service Provider. HomeWorks Connect recently acquired the 138.43.60.0/22 subnet to serve our customers with FTTH Internet service. If you do a search at ARIN, you'll find that this subnet is now registered to HomeWorks Connect at 7973 E Grand River Ave, Portland, MI, United States. HomeWorks Connect is a division of HomeWorks Tri-County Electric Cooperative, located at the same address. Tri-County Electric Cooperative was formed in 1937 to provide electricity to rural mid-Michigan, and since then we've grown to serve over 27,000 homes and businesses.
Please remove the 138.43.60.0/22 subnet from your bot-blocking service and feel free to contact me if you have any questions.
Thanks,
Tom Manting, CIO
HomeWorks
tmanting@homeworks.org
517-647-1236

**Comment by mitchellkrogza** [comment] 2020-02-20 06:45
Hi there @tmanting I cannot find the `138.43.60.0` range listed anywhere. Please can you point me to where it's listed.

**Comment by tmanting** [comment] 2020-02-20 13:10
Hi Mitchell,
I can't. This was reported to me by one of your customers. I've included
the email that I received from them and I wish I could be more helpful.
Thanks for your attention to this matter,
-Tom

From: Andrew Brown <abrown@kennedyc.com>
Date: Wed, Feb 19, 2020 at 1:09 PM
Subject: 138.43.60.0/22 block culliganlansing.com
To: <tmanting@homeworks.org>


Hi Tom,

My name is Andy Brown and I work for Kennedy Communications.  We are the
hosting company for culliganlansing.com.  I was forwarded your email about
a customer of yours being unable to access culliganlansing.com and being
hit with a 403 Forbidden Response.

I've dug into this and found that the entire 138.43.0.0/16 block is being
denied by our web server because it was included in a "bad bot blocker".
I've removed the entry, so you should be able to access it now.  Please
confirm and let me know it is working for you.

We use https://github.com/mariusv/nginx-badbot-blocker to automatically
pull in a blacklist for IPs. You may want to send a PR into them to let
them know you recently purchased this IP block, and these are no longer bad
IPs.

Thanks,

-- 
*Andrew Brown* | *Senior Web Developer*
*Kennedy Communications*
D: 608-443-0976 | abrown@kennedyc.com
9 Odana Ct Suite 200 | Madison, WI 53719

Like KennedyC on Facebook! <https://www.facebook.com/TheKennedyC>

**Comment by mitchellkrogza** [comment] 2020-02-21 14:01
Hi @tmanting its definitely not listed anymore. The list of IP's that are blocked changes daily and is pulled from the top blacklisted IP's from badips.com so at some point some of your IP's were listed there. Can you confirm the problem is no longer occuring?

If it is still occurring then Kennedy Communications needs to check they have the latest update of the blocker.

**Comment by mitchellkrogza** [comment] 2020-02-21 14:31
Hi @tmanting I just noticed Kennedy is still using a very old version of a different blocker which I used to contribute to but haven't had time in a long while to update that repo. I will try update that repo with the latest version but this one is always up to date.

**Comment by tmanting** [comment] 2020-02-21 14:34
Thank you, Mitchell. Our customer is fine but I always follow up on these
because you never know what future issues I may be avoiding by doing so.

**Comment by mitchellkrogza** [comment] 2020-02-21 14:40
Hi @tmanting just Fixed on Marius's repo, they are really using a very old version of the blocker which is not being maintained as much as this. See - https://github.com/mariusv/nginx-badbot-blocker/commit/05f6e53be8507333a0c346f0f42a0e72c737bde7

**Closed** 2020-03-09 12:44 UTC
Labels: Referrers / Domains

**Comment by browner12** [comment] 2020-08-06 20:27
Hi. I'm the one who initially suggested to Tom to post here.  Is it recommended to no longer use the `mariusv` repo?

We are running into another set of blocked IPs, which is what caused me to revisit this.
